//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ООО__Моделька_.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int EmployeeID { get; set; }
        public int EmployeeRoleID { get; set; }
        public string EmployeeFullName { get; set; }
        public string EmployeeMail { get; set; }
        public string EmployeePassword { get; set; }
        public string EmployeePhoneNumber { get; set; }
        public int EmployeeStatus { get; set; }
        public System.DateTime EmployeeEmploymentDate { get; set; }
        public byte[] EmployeePhoto { get; set; }
        public string EmployeeNotes { get; set; }
    
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
